### ISSUE TITLE
Cursor is not displayed for wide chars

### ISSUE THREAD

**Issue by w23** [w23/alacritty#20]
That's because we render them using rects which are not aware of cursor at all.
Figure out what to do.

**Comment by kchibisov** [comment]
It still seems like wide cursor is broken, but in a bit different way, the cell from where I come to a wide char uses old colors or something like that. It's very easy to notice with inverted cursor and colored wide chars.

![picture](https://user-images.githubusercontent.com/27620401/94721749-f9577680-035e-11eb-812f-195507d2ee0b.png)

**Comment by kchibisov** [comment]
That black box isn't my cursor and it shouldn't be there, my cursor is over crab.

**Comment by w23** [comment]
ah yes, this is likely because the old cursor position is not cleared
